AppBundle\Entity\Websites:
    type: entity
    table: websites
    uniqueConstraints:
        url_UNIQUE:
            columns:
                - url
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        url:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        status:
            type: string
            nullable: false
            length: 10
            options:
                fixed: false
        created:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
        updated:
            type: datetime
            nullable: false
            options:
                default: '0000-00-00 00:00:00'
    lifecycleCallbacks: {  }
